---

- hosts: db
  become: yes
  gather_facts: yes
  roles:
    - db
  tags: deploy-db

- hosts: webapp
  become: yes
  gather_facts: yes
  roles:
    - web

- hosts: command
  become: yes
  gather_facts: yes
  roles:
    - db
  tags: deploy-command