---

- name: Update apt-get
  apt:
    update_cache: yes

- name: Install git
  apt:
    name: git
  tags: install-git

- name: Allow agent forwarding
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowAgentForwarding yes
  notify: restart ssh
  tags: sshd_config
