---

- name: run debug msg
  debug:
    msg: "{{ item }}"
  with_items:
    - "[[ ansible_distribution }}"
    - "{{ ansible_distribution_release }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_kernel }}"