---

- name: Clone git repository (ecso-web)
  git:
    repo: "{{ ecso_web.repository }}"
    accept_hostkey: yes
    clone: yes
    dest: /home/ansible_user/ecso-web
    version: "{{ ecso_web.version }}"
    force: yes
  become: no

- name: Fix git detached HEAD (ecso-web)
  command: "{{ item }}"
  with_items: 
  - git branch temp
  - git checkout temp
  - git branch -f master temp
  - git checkout master
  - git branch -d temp
  args:
    chdir: /home/ansible_user/ecso-web

- name: Replace env.prod with template (ecso-web)
  template:
    src: env.prod.j2
    dest: /home/ansible_user/ecso-web/env.prod
    owner: ansible_user
    mode: 0644

- name: Add new env.prod file to git repository and commit (ecso-web)
  command: "{{ item }}"
  with_items: 
  - git add env.prod
  - git commit -m "New version"
  args:
    chdir: /home/ansible_user/ecso-web

# - name: Login to heroku (ecso-web)
#   expect:
#     command: heroku login -i
#     chdir: /home/ansible_user/ecso-web
#     responses:
#       Email: "{{ heroku_username }}"
#       Password: "{{ heroku_password }}"
#       Logged: 
#     echo: yes
#     timeout: 10
#   register: output
# - debug: var=output

- name: Push to heroku master (ecso-web)
  expect:
    command: git push -f heroku master
    chdir: /home/ansible_user/ecso-web
    timeout: 300
    responses:
      Username: ''
      Password: "{{ heroku_apikey }}"
  register: output
- debug: var=output.stdout_lines
