---

- name: Current version of database
  command: mongo -u "{{ mongo_admin }}" -p "{{ mongo_admin_password }}" --authenticationDatabase admin --quiet --eval "db.databaseVersioning.find().sort({_id":" -1}).limit(1)" "{{ db_name }}"
  register: result
  
- name: Save in variable
  set_fact:
    result_var: "{{ result.stdout | from_json }}"

- name: Make local db.version variable
  set_fact:
    version_local: "{{ db.version }}"

- name: Correct local version variable 
  set_fact:
    version_local: "{{ result_var._id + 1 }}"
  when: result_var._id >= db.version
  
- name: Clone git repository
  git:
    repo: git@bitbucket.org:ecsoteam/db_scripts.git
    accept_hostkey: yes
    clone: yes
    dest: /home/ansible_user/db_scripts
  become: no
  when: result_var._id < db.version

- name: Add filenames to variables list 1
  find:
    paths: "/home/ansible_user/db_scripts/{{ env }}"
    patterns: "{{ item }}-*.js"
  with_sequence: start="{{ result_var._id + 1 }}" end="{{ version_local }}" format=%d
  register: output
  when: result_var._id < db.version
      
- name: Add filenames to variables list 2
  set_fact:
    fileslist="{{ fileslist|default([]) + [ item.files[0].path ] }}"
  loop: "{{ output.results }}"
  when: result_var._id < db.version

- name: Print list of js files
  debug:
    var: fileslist
  when: result_var._id < db.version

- name: Run js files in mongo
  command: mongo -u "{{ mongo_admin }}" -p "{{ mongo_admin_password }}" --authenticationDatabase admin "{{ db_name }}" "{{ item }}"
  loop: "{{ fileslist }}"
  when: result_var._id < db.version

