# Made from template
FROM node:8.11-alpine

# Listen port {{ api_port }}
EXPOSE {{ api_port }}

# Create directory 
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy sources
COPY src /app

# Define environment variables
ENV NODE_ENV=production MONGO_HOST={{ mongo_host }} MONGO_PORT={{ mongo_port }} MONGO_DB={{ db_name }} MONGO_USER={{ mongo_writer }} MONGO_PASS={{ mongo_writer_password }} API_PORT={{ api_port }} API_SERVER_HOST={{ api_server_host }} API_SERVER_CORS={{ api_server_cors }} API_CONTEXT_ROOT={{ api_context_root }} API_JWT_SECRET={{ api_jwt_secret }} API_JWT_EXPIRES_IN={{ api_jwt_expires_in }}

# Run node
CMD [ "node", "index.js" ]