# Made from template
FROM node:8.11-alpine

# Listen port {{ api_port }}
EXPOSE {{ api_port }}

# Create directory 
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy sources
COPY src /app

# Define environment variables
ENV MONGO_HOST={{ mongo_host }} MONGO_PORT={{ mongo_port }} MONGO_DB={{ db_name }} MONGO_USER={{ mongo_user }} MONGO_PASS={{ mongo_user_password }} API_PORT={{ api_port }}

# Run node
CMD [ "node", "index.js" ]