FROM node:8.11-alpine

# Create directory 
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy sources
COPY src /app

# Define environment variables
ENV NODE_ENV=production MONGO_HOST={{ mongo_host }} MONGO_PORT={{ mongo_port }} MONGO_DB={{ db_name }} MONGO_USER={{ mongo_writer }} MONGO_PASS={{ mongo_writer_password }}

# Apply cron job
RUN echo "{{ rotate_travels.scheduler }} node /app/index.js" >> /app/crontab
RUN crontab /app/crontab

CMD ["crond", "-f", "-L", "/dev/stdout"]