---

- name: Clone git repository (deploy-hotel-prices)
  git:
    repo: "{{ hotel_prices.repository }}"
    accept_hostkey: yes
    clone: yes
    dest: /home/ansible_user/hotel-prices
    version: "{{ hotel_prices.version }}"
    force: yes
  become: no

- name: Replace Dockerfile (deploy-hotel-prices)
  template:
    src: Dockerfile-hotel.j2
    dest: /home/ansible_user/hotel-prices/Dockerfile
    owner: ansible_user
    mode: 0644

- name: Build docker image (deploy-hotel-prices)
  docker_image:
    force: yes
    name: hotel-prices
    tag: "{{ hotel_prices.version }}"
    path: /home/ansible_user/hotel-prices

- name: Run built image (deploy-hotel-prices)
  docker_container:
    name: hotel-prices
    image: "hotel-prices:{{ hotel_prices.version }}"
    state: started
    restart_policy: "always"
