---

- name: Update apt-get
  apt:
    update_cache: yes

- name: Add Mongo packages repo
  apt_key: id=68818c72e52529d4  keyserver=keyserver.ubuntu.com
- name: Add repo itself
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/4.0 multiverse' state=present                                      
- name: Install packages
  apt: pkg=mongodb-org-shell state=present