---

- name: Check for existing db on server
  shell: mongo -u "{{ mongo_admin }}" -p "{{ mongo_admin_password }}" --authenticationDatabase admin --eval "db.getMongo().getDBNames()" | grep -o "{{ db_name }}"
  ignore_errors: yes
  register: database
  
- name: Create ECSO database
  command: mongo --eval "db = db.getSiblingDB('"{{ db_name }}"').createCollection('databaseVersioning')"
  when: database.stdout == ""

- name: Add 0 version
  command: mongo --eval "db.databaseVersioning.insertOne({_id":" NumberInt(0), notes":" 'Clean database'})" "{{ db_name }}"
  when: database.stdout == ""