---

- hosts: command
  become: yes
  gather_facts: no
  roles:
    - db
  tags: deploy-db

- hosts: docker
  become: yes
  gather_facts: no
  roles:
    - docker
  tags: deploy-docker

- hosts: command
  become: yes
  gather_facts: no
  roles:
    - heroku
  tags: deploy-heroku
